Repository cedvdb/phone_form_field, pull requests merged in 2021-10, with the labels that each got.

#55 Unfixed dialcode
  CHANGELOG.md
  README.md
  example/lib/main.dart
  lib/phone_form_field.dart
  lib/src/models/country_code_visibility.dart
  lib/src/widgets/phone_field.dart
  lib/src/widgets/phone_field_ui_builder.dart
  lib/src/widgets/phone_form_field.dart
Labels: 4.0.0

#57 Update doc
  README.md
  docs/flutter_service_worker.js
  docs/index.html
  docs/main.dart.js
Labels: 4.0.0

#58 4.0.0
  README.md
  docs/flutter_service_worker.js
  docs/index.html
  docs/main.dart.js
Labels: 4.0.0

#59 Minimize code duplication
  lib/src/widgets/country_picker/country_selector.dart
  lib/src/widgets/country_picker/country_selector_navigator.dart
Labels: 4.0.1

#68 4.2.0
  CHANGELOG.md
  README.md
  example/lib/main.dart
  example/pubspec.lock
  lib/src/validator/phone_validator.dart
  lib/src/widgets/phone_form_field.dart
  pubspec.yaml
  test/phone_form_field_test.dart
  test/phone_validator_test.dart
Labels: 4.2.0
