Repository cedvdb/phone_form_field, pull requests merged in 2022-04, with the labels that each got.

#92 refactor folder structure
  CHANGELOG.md
  README.md
  example/lib/main.dart
  example/pubspec.lock
  lib/phone_form_field.dart
  lib/src/validator/phone_validator.dart
  lib/src/widgets/country_selector/country_list.dart
  lib/src/widgets/country_selector/country_selector.dart
  lib/src/widgets/country_selector/country_selector_navigator.dart
  lib/src/widgets/country_selector/search_box.dart
  lib/src/widgets/phone_field.dart
  lib/src/widgets/phone_field_state.dart
  lib/src/widgets/phone_form_field.dart
  lib/src/widgets/phone_form_field_state.dart
  pubspec.yaml
  test/_country_selector_navigator_test.dart
  test/_country_selector_test.dart
Labels: 4.6.0

#93 refactor folder structure (#92)
  CHANGELOG.md
  README.md
  example/lib/main.dart
  example/pubspec.lock
  lib/phone_form_field.dart
  lib/src/validator/phone_validator.dart
  lib/src/widgets/country_selector/country_list.dart
  lib/src/widgets/country_selector/country_selector.dart
  lib/src/widgets/country_selector/country_selector_navigator.dart
  lib/src/widgets/country_selector/search_box.dart
  lib/src/widgets/phone_field.dart
  lib/src/widgets/phone_field_state.dart
  lib/src/widgets/phone_form_field.dart
  lib/src/widgets/phone_form_field_state.dart
  pubspec.yaml
  test/_country_selector_navigator_test.dart
  test/_country_selector_test.dart
Labels: 4.6.0

#96 Forward hintStyle to the inner InputDecoration
  lib/src/widgets/phone_field_state.dart
Labels: 5.0.0

#102 feat: add greek internationalization
  lib/l10n/el.arb
Labels: 5.0.2

#107 5.0.3
  CHANGELOG.md
  lib/phone_form_field.dart
  lib/src/models/phone_controller.dart
  lib/src/widgets/phone_form_field.dart
  lib/src/widgets/phone_form_field_state.dart
Labels: 5.0.3
